// <auto-generated />
namespace GitBan.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class BoardData : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207172231530_BoardData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so8+L9km2HEvDj9LjssgIidd5ef6eGO08BEYf2b6ot1PCqr1+c73KucfPPvqqyWu/BbX5vfLr4AP66GVdrfK6vX6Vn+t7Z7OP0rvhe3e7L9rXvHfQNf22bO/tfZS+WJdlNinpg/OsbPKP0tWnj163VZ1/ni/zOmvz2cusbfN6iXdzRl1J8Gj16e2o8PDuzh6ocDdbLqs2a2lye4h30MS/BtHXbU188lH6rHiXz57ny4t2bpH9IntnPqFfP0q/WhbEVvRSW69zf3Dy9+ZOj6fTvGneVG/z5Q+/78uszeqv6vJnuefHdx37bWTKJ1VWz35ec+WtSXVSlevF8uc1rfpoMv/cjOtmIK+ruv2ynpF6/CAwPyfa5LvF6nmxKNr3Qf3WLHfWNITBjzjOR1PE8GZkfxZYbvO8kePRZgVRRrsQ5+IpKXx8k79rOxMpb73OW88/ICfEdSGeyJj9hu5wui+zHMbeFgV/0+tC1Nj7qvVuAsCcGntfWDhKRksw+93ju+Kj6QeP7w44c4+/yFYrkm/PudNP0tfi2Z1sv35/F24hMO5Om4gnZ7G1PZEoZBd551vQcpY/K+qmxdRPMjDRyWzRa3Zr9jD9+VzS1QCO7KY1fvf5UJ3ccd8LZQD62jMa0YJEmQenQyMUYs6rvvh6mpVZ"
                       + "HVElwjhD6mjT26LH/fflk9tDCFw8H1DwxXvAc25bAM193If1+G6Hpt0585SJtuwo7C4H3Io/VBF8fQaJeIQM4SYOGXjvw1jk54iIRh1+fSrGnEUGcRMZh178MDoOvW3dNx+E/fD2cDxz6kPyPr49rA8Xf+eT+VDcp/+v4TO1ml+fzSIOIkO4icsG3vvZYTLnsfkw3Ke3h/R12OxndWp7rky3ie1dP7F/W1dG3YgvfP+Gx99NVvX8CmnyUUpEuixm8CleXzdtvhijwfj1LypPyoLG6xp8kS2L87xp2f5R4o3cnq+f9LKue9PMyv83Zr4KDP3GeOU94wZRRdLB8jKrp/Os3lpk7+68b9wYyUJ9GLxuZuk9oN06Hv05yhZ9AzN56yH+XGV5voEx9sF3sjPcx3uC6AXKQ0B+KFLTzbbcjMytJ/7nKNfyszLv3RzJzWT6Rib+/fIj/Tg5xMeaXd+KDKVHxBZ+9tFsUhG+gqEmVDrD7ILVBEkPrn4eA2ySLTdANqmTHmjzRQy2zcTcAFzzKj3Y+nkMtMnRxKbsFrmYvqPy+K6/9vb4ad4UFw4EVuKW+RQ5PQfUtDlbnleG4WhQPkamSYcfv8jbbEaccly3xXk2belrWFDO8v5kVq6pyeliks/Oll+u29W6PW6afDEpr/3xPr67uX9OOIU4P/5yhb88z+zrD4HQLGgI+ZfLJ+uinFm8n0VEaQAEhEYVBWFFWW4Cd3FtIb2olrcEpOR7mq/yJdTMm3yxKglY8+XydXaZD+N2Mw1Dij1+WmQXdbZoFIZ7n/4k9qOF3KP/JwAA//9pVGuaPR4AAA=="; }
        }
    }
}
