// <auto-generated />
namespace GitBan.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207040258594_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so8+L9km2HEvDj9LjssgIidd5ef6eGO08BEYf2b6ot1PCqr1+c73KucfPPvqqyWu/BbX5vfLr4AP66GVdrfK6vX6Vn+t7Z7OP0rvhe3e7L9rXvHfQNf22bO/tfZS+WJdlNinpg/OsbPKP0tWnj163VZ1/ni/zOmvz2cusbfN6iXdzRl1J8Gj16e2o8PDuzh6ocDdbLqs2a2lye4h30MS/BtHXbU188lH6rHiXz57ny4t2bpH9IntnPqFfP0q/WhbEVvRSW69zf3Dy9+ZOj6fTvGneVG/z5Q+/78uszeqv6vJnuefHdx379ZmSRKTNCpp3xUrE4Cmhhm/yd22HTeWt13nrcTKJi+tCZGbMHB7Fw/bopPGuiKMR27sDcvv4i2y1IhJ5cqyfpK9FiE+2X7+/tC4Ext1pExFai63tiSQlu8g731LXhOmzom5a0G6SYdJOZotes1vT1/Tnk7mrIBzVTWv87k+k6rNxX+EwAH3tGY1oQZLOg9OhEQoxPaUvvp5mZVZHNM1JVa4XyyFtteltUQD++/LJ7SEE0uwDCr54D3hOQgNo7uM+rMd3OzTtzpknjdqyo8+7HLBJhLpNbO9WlDoi81jZ92Z72ONnafJRSkS6LGbg5dfXTZsvxmgwfv2LypOyoPG6Bl9ky+I8b1qm"
                       + "O9l2Erevb1etRWmaWfn/RuNaYOg3mtGe7b29UVxeZvV0ntVbi+zdnfc2Nn1D92HwusbrPaC9n0Hq69WbDdKgPRIe/uyj2aQixAVBtWBf01T15enxXd8Lffw0b4oLBwI+6TKfwiNyQE2bs+V5ZQhNI/IxMk068/BF3mYzIsxx3Rbn2bSlrzHR7Ef8ZFauqcnpYpLPzpZfrtvVuj1umnwxKa/98T6+u7l/tschzo+/XOEvT4F8/SEQmgUNIf9y+WRdlDOL97O+gAyBAI+o1BFW5EcRuItrC+lFtbwlICXf03yVLyGzb/LFqiRgzZfL19llPozbzTQMKfb4aZFd1NmiURjuffqT2I9CmqP/JwAA//+fqJDVRw0AAA=="; }
        }
    }
}
